config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  
  devise_for 	:users, 
  						:path => '', 
  						:path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
  						:controllers => {:omniauth_callbacks => 'omniauth_callbacks',
  						                  :registrations => 'registrations'
  					                  	}
  						                
            #creates shortcuts to access pages without having to type full path name e.g/users/login
            #allows users to edit information on their profile


  resources :users, only: [:show] #only one path in rake routes
  resources :rooms #multiple paths in rake routes
  resources :photos
  
  resources :rooms do
    resources :reservations, only: [:create] #stops users updating/destroying reservation
  end
  
  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'
  
  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'
  
  get '/search' => 'pages#search'

end 

app/views/pages/home.html.erb
<%= form_tag search_path, method: :get do %>
	<div class="row">
		<div class="col-md-6">
			<%= text_field_tag :search, params[:search], placeholder: "Where are you going?", class: "form-control" %>
		</div>
		<div class="col-md-2">
			<%= text_field_tag :start_date, params[:start_date], placeholder: "Start Date", class: "form-control" %>
		</div>
		<div class="col-md-2">
			<%= text_field_tag :end_date, params[:end_date], placeholder: "End Date", class: "form-control" %>
		</div>
		<div class="col-md-2">
			<%= submit_tag "Search", class: "btn btn-primary" %>
		</div>
	</div>
<% end %>

<br>

<div class="text-center">
	<h2>Hello World ;)</h2>
	<p>Discover new and exciting places.</p>
</div>

<br>

<div class="row">
	<div class="col-md-4 col-sm-12">
		<a href= "http://localhost:3000/search?utf8=✓&search=dubai">
		<div class="discovery-card" style="background-image: url('/assets/Dubai.jpg')">
			<div class="va-container">
				<div class="va-middle text-center">
					<h2><strong>Dubai</strong></h2>
				</div>
			</div>
		</div>
		</a>
	</div>

	<div class="col-md-4 col-sm-6">
		<a href= "http://localhost:3000/search?utf8=✓&search=london">
		<div class="discovery-card" style="background-image: url('/assets/London.jpg')">
			<div class="va-container">
				<div class="va-middle text-center">
					<h2><strong>London</strong></h2>
				</div>
			</div>
		</div>
		</a>
	</div>

	<div class="col-md-4 col-sm-6">
		<a href= "http://localhost:3000/search?utf8=✓&search=sydney">
		<div class="discovery-card" style="background-image: url('/assets/Sydney.jpg')">
			<div class="va-container">
				<div class="va-middle text-center">
					<h2><strong>Sydney</strong></h2>
				</div>
			</div>
		</div>
	</div>
	</a>
</div>

<br>

<div class="text-center">
	<h2>More of a Homebird?</h2>
	<p>Search something more local.</p>
</div>

<br>

<div class="row">
	<% @rooms.each do |room| %>

		<div class="col-md-4">
			<div class="panel panel-default">
				<div class="panel-heading preview">
					<%= image_tag room.photos[0].image.url(:medium) if room.photos.length > 0 %>
				</div>
				<div class="panel-body">
					<%= link_to room.listing_name, room %>
				</div>
			</div>
		</div>

	<% end %>
</div>

<script>
	$(function() {
		$("#start_date").datepicker({
			dateFormat: 'dd-mm-yy',
			minDate: 0,
			maxDate: '3m',
			onSelect: function(selected) {
				$('#end_date').datepicker("option", "minDate", selected);
				$('#end_date').attr('disabled', false);
			}
		});

		$("#end_date").datepicker({
			dateFormat: 'dd-mm-yy',
			minDate: 0,
			maxDate: '3m',
			onSelect: function(selected) {
				$('#start_date').datepicker("option", "maxDate", selected);
			}
		});
	})


</script>

app/views/pages/search.html.erb
<%# Search function %>
<div id="wrapper">
	
	

	<div id="article">
		
		<div class="row">
			<%= search_form_for @search, url: search_path do |f| %>
				
				<div class="row">
					<div class="col-md-3">
						<%= text_field_tag :start_date, params[:start_date], placeholder: "Start Date", class: "form-control" %>
					</div>
					<div class="col-md-3">
						<%= text_field_tag :end_date, params[:end_date], placeholder: "End Date", class: "form-control" %>
					</div>
					<div class="col-md-3">
						<%= f.text_field :price_gteq, placeholder: "Min Price", class: "form-control" %>
					</div>
					<div class="col-md-3">
						<%= f.text_field :price_lteq, placeholder: "Max Price", class: "form-control" %>
					</div>
				</div>

				<hr>

				<div class="row">
					<div class="col-md-4">
						<%= check_box_tag "q[room_type_eq_any][]", "Entire" %> Entire Room
					</div>
					<div class="col-md-4">
						<%= check_box_tag "q[room_type_eq_any][]", "Private" %> Private Room
					</div>
					<div class="col-md-4">
						<%= check_box_tag "q[room_type_eq_any][]", "Shared" %> Shared Room
					</div>
				</div>

				<hr>

				<div class="row">
					<div class="col-md-4">
						<div class="form-group">
							<label>Accommodate</label>
							<%= f.select :accommodate_gteq, [["1",1], ["2",2], ["3",3], ["4",4], ["5",5], ["6+",6]], prompt: "Select...", class: "form-control" %>
						</div>
					</div>

					<div class="col-md-4">
						<div class="form-group">
							<label>Bedrooms</label>
							<%= f.select :accommodate_gteq, [["1",1], ["2",2], ["3",3], ["4+",4]], prompt: "Select...", class: "form-control" %>
						</div>
					</div>

					<div class="col-md-4">
						<div class="form-group">
							<label>Bathrooms</label>
							<%= f.select :accommodate_gteq, [["1",1], ["2",2], ["3",3], ["4+",4]], prompt: "Select...", class: "form-control" %>
						</div>
					</div>
				</div>

				<hr>

				<div class="row">
					<div class="col-md-4">
						<%= check_box_tag "q[is_tv_eq]", true %> TV
					</div>
					<div class="col-md-4">
						<%= check_box_tag "q[is_kitchen_eq]", true %> Kitchen
					</div>
					<div class="col-md-4">
						<%= check_box_tag "q[is_internet_eq]", true %> Internet
					</div>
					<div class="col-md-4">
						<%= check_box_tag "q[is_heating_eq]", true %> Heating
					</div>
					<div class="col-md-4">
						<%= check_box_tag "q[is_air_eq]", true %> Air Conditioning
					</div>
				</div>

				<br>

				<div class="row">
					<%= f.submit "Search", class: "btn btn-primary" %>
				</div>

			<% end %>

			<hr>

			<div class="row">
				<% @arrRooms.each do |room| %>
					
					<div class="col-md-4">
						<div class="panel panel-default">
							<div class="panel-heading preview">
								<%= image_tag room.photos[0].image.url(:medium) if room.photos.length > 0 %>
							</div>
							<div class="panel-body">
								<%= link_to room.listing_name, room %>
							</div>
						</div>
					</div>

				<% end %>
			</div>


		</div>

	</div>

</div>

<script>
	$(function() {
		$("#start_date").datepicker({
			dateFormat: 'dd-mm-yy',
			minDate: 0,
			maxDate: '3m',
			onSelect: function(selected) {
				$('#end_date').datepicker("option", "minDate", selected);
				$('#end_date').attr('disabled', false);
			}
		});

		$("#end_date").datepicker({
			dateFormat: 'dd-mm-yy',
			minDate: 0,
			maxDate: '3m',
			onSelect: function(selected) {
				$('#start_date').datepicker("option", "maxDate", selected);
			}
		});
	})
</script>